name: Build and deploy a new staging release to a Kubernetes cluster with kubectl
on:
  workflow_dispatch:
    inputs:
      default_bump:
        description: Which type of bump to use if no conventional changelog found (major, minor or patch)
        required: false
        default: minor

jobs:
  build-main-docker-kubernetes:
    name: Build and deploy
    environment: staging
    runs-on: ubuntu-20.04
    env:
      DEPLOYMENT_NAME: <CHANGE ME>

    steps:
      - name: Check branch is main
        if: github.ref != 'refs/heads/main'
        run: echo 'Please run this workflow on main branch'; exit 1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge develop into main
        id: merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git fetch origin develop
          git merge origin/develop --ff-only
          git push origin main
          echo "::set-output name=merge_sha::$(git log -1 --format='%H')"

      - name: Bump version and push tag
        id: version
        uses: amplifysa/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: ${{ steps.merge.outputs.merge_sha }}
          release_branches: main
          create_annotated_tag: true
          default_bump: ${{ github.event.inputs.default_bump }}

      - name: Add version.txt into the code
        run: echo ${{ steps.version.outputs.new_version }} > version.txt

      - name: Docker login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          no-cache: true
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.new_version }}
            ghcr.io/${{ github.repository }}:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_YANN }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_YANN }}
          aws-region: eu-central-1

      - name: Deploy to kubernetes cluster
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA_YANN }}" | base64 -d > kube.config
          kubectl --kubeconfig=./kube.config set image deployment/${{ env.DEPLOYMENT_NAME }} \
            ${{ env.DEPLOYMENT_NAME }}=ghcr.io/${{ github.repository }}:${{ steps.version.outputs.new_version }}
          kubectl --kubeconfig=./kube.config rollout status deployment/${{ env.DEPLOYMENT_NAME }}
