name: Build and deploy a new staging release to Heroku
on:
  workflow_dispatch:
    inputs:
      default_bump:
        description: Which type of bump to use if no conventional changelog found
        required: false
        default: minor

jobs:
  build_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      HEROKU_APP: amplify-<<CHANGE ME>>-staging

    steps:
      - name: Check branch is main
        if: github.ref !== 'refs/heads/main'
        run: echo 'Please run this workflow on main branch; exit 1

      - name: Bump version and push tag
        id: version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          create_annotated_tag: true
          default_bump: ${{ github.event.inputs.default_bump }}

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Add version.txt into the code
        run: echo ${{ steps.version.outputs.new_version }} > version.txt

      - name: Docker login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker login to Heroku
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          no-cache: true
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.new_version }}
            registry.heroku.com/${{ env.HEROKU_APP }}/web

      - name: Install Heroku cli
        run: curl https://cli-assets.heroku.com/install.sh | sudo sh

      - name: Deploy to Heroku staging
        run: HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku container:release web --app ${{ env.HEROKU_APP }}
