name: Test project
on: [ push, pull_request ]

jobs:
  test-node-python:
    name: Lint and test
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "16"
      PYTHON_VERSION: "3.9.7"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm modules
        run: npm install

      - name: Run npm linter
        run: npm run lint

      - name: Run npm tests
        run: npm run test

      - name: Setup python
        # Used by "Cache pipenv"
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}

      - name: Install python dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev

      - name: Run python linter
        run: pipenv run flake8 .

      - name: Run python tests
        run: pipenv run pytest
